name: Swift CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build
      run: xcodebuild clean build -workspace IrregularVerbs/IrregularVerbs.xcworkspace -scheme IrregularVerbs/IrregularVerbs
    - name: Run tests
      run: xcodebuild test -workspace IrregularVerbs/IrregularVerbs.xcworkspace -scheme IrregularVerbs/IrregularVerbs
